services:
  devday_db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: devday
    volumes:
      - data-devday:/var/lib/postgresql/data

  mailcatcher:
    build:
      context: ./docker/development/mailcatcher
    ports:
    - 127.0.0.1:1080:1080/tcp
    - 127.0.0.1:1025:1025/tcp
    restart: always

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - data-redis:/data
version: '3.0'
volumes:
  data-devday: {}
  redis: {}
